let name = "John";
let val1=23;
let val2=34.5;
let isdatavalil=true;
let nodata=null;
let a;
console.log(name);
console.log(val1);
console.log(val2);
console.log(isdatavalil);
console.log(nodata);
console.log(a);